### PR TITLE
added QR scanner, iOS platform config to test with and basic app info…

### PR DESCRIPTION
**Pull request by bokova**
… to config.xml to run the iOS deploy.
Note camera will actually work only on device. On the desktop browser, has an alternative workflow w/o the camera

### CODE REVIEW

**Comment by bokova** [comment]
Someone please test and merge

**Comment by chill117** [comment]
What's the different flow for the desktop browser? Can you share a link for more info?

**Comment by karliatto** [comment]
I tried it on my device and nothing is happening.

**Comment by bokova** [comment]
@chill117 - if you do 'cordova run browser' to run it in the Browser, then the plugin asks you for the QR value instead of fetching the image from the camera.

@karliatto which steps did you take to make it run? Did you try running 'cordova run browser' in the project folder? To be properly functional it needs to run on a mobile device though. I only prepared it for iOS deployment, and if I recall correctly you don't have a machine with Xcode, so that won't work for you. Right? Perhaps you could build it for Android but I haven't tried that yet. Would be best do discuss in person though I'm ill and won't be there on Monday most likely

**Pull request merged**
