### PR TITLE
Address query, jquery version

### PR DESCRIPTION
**Pull request by ipovalyaev**
A more lightweight version using jquery instead of 3rd party framework

### CODE REVIEW

**Comment by karliatto** [comment]
This one is working in my device, but the other with the plugin I didn't make to work.

**Comment by ipovalyaev** [comment]
Somehow on mine device both are working. This one is better anyway, so let's use this one after Charlie's review, I'll cancel the poll request for another.

**Review by chill117 — CHANGES_REQUESTED** [review]
* [ ] Shouldn't include jQuery in git. It is available via npm:
```bash
npm init
npm install --save jquery
```
This will create a package.json file for the project and add jquery as a dependency.

* [ ] `query_bc(address)` should take a callback function as the second argument and should call the callback function (in case of an error) or with the balance (in case of success). For example:
```js
function query_bc(address, cb) {
    jQuery.ajax().then(function(data, status, xhr) {
        // Check for an error with the request.
        // Call cb with an error like this:
       cb(error);
       // Or if successfully got the balance:
       cb(null, balance);
    });
}
```

Then we can use the `query_bc` function like this:
```js
query_bc('SOME_BTC_ADDRESS', function(error, balance) {
    if (error) {
        // Show the error to the user.
    } else {
        // Success!
        // Show the balance to the user.
    }
});
```

**Comment by ipovalyaev** [comment]
Seems it's a problem to include jquery from npm by this way -- cordova doesn't include node_modules folder in apk. Maybe some magic tricks could be used, but let's make a separate issue for this research :)

**Pull request merged**
